name: Publish 'faulegal' Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fau-cdi/odbcd:withfaulegal
  PLATFORMS: linux/amd64
  GO_VERSION: '~1.25'
  GO_STABLE: 'true'
  NODE_VERSION: '25'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run 'make deps'
        run: make deps
      - name: Run 'make generate'
        env:
          LEGAL_HTML: "For legal reasons we must link to our <a href='https://www.cdi.fau.de/imprint/'>Imprint</a>, <a href='https://www.cdi.fau.de/en/privacy/' rel='noopener noreferer' target='_blank'>Privacy Policy</a> and <a href='https://www.cdi.fau.de/en/accessibility/' rel='noopener noreferer' target='_blank'>Accessibility</a> pages."
        run: make generate
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true